homeassistant:
  name: Mylke
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Amsterdam
  currency: EUR
  packages: !include_dir_named include #theme

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# LoveLace frontend
lovelace:
  mode: yaml
  resources: 
    [ 
#      { url: /hacsfiles/apexcharts-card/apexcharts-card.js,                         type: module },
      { url: /hacsfiles/bar-card/bar-card.js,                                       type: module },
      { url: /hacsfiles/button-card/button-card.js,                                 type: module },
      { url: /hacsfiles/kiosk-mode/kiosk-mode.js,                                   type: module },
      { url: /hacsfiles/light-entity-card/light-entity-card.js,                     type: module },
      { url: /hacsfiles/light-popup-card/light-popup-card.js,                       type: module },
      { url: /hacsfiles/lovelace-layout-card/layout-card.js,                        type: module },
      { url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js,            type: module },
      { url: /hacsfiles/lovelace-card-mod/card-mod.js,                              type: module },
      { url: /hacsfiles/swipe-card/swipe-card.js,                                   type: module },
      { url: /local/font.css,                                                       type: css    }]


# Spotify integration
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# Browser_mod config
browser_mod:
  prefix: browser_

# Slide curtain integration
slide:
  username: !secret slide_username
  password: !secret slide_password
  invert_position: true
