button_card_templates: !include button_card_templates.yaml

views:
  - type: custom:grid-layout
    path: 0
    layout:
      #default
      grid-gap: var(--custom-layout-card-padding)
      grid-template-columns: repeat(4, 1fr) 0
      grid-template-rows: 0 repeat(2, fit-content(100%)) 0fr
      grid-template-areas: |
        "sidebar  .           .           .           ."
        "sidebar  kitchen     livingroom  livingroom  ."
        "sidebar  media       other       flows       ."
        "sidebar  .           .           .           ."
      mediaquery:
        #phone
        "(max-width: 800px)":
          grid-gap: calc(var(--custom-layout-card-padding) * 1.7)
          grid-template-columns: 0 repeat(2, 1fr) 0
          grid-template-rows: 0 repeat(5, fit-content(100%)) 0fr
          grid-template-areas: |
            ".  .           .           ."
            ".  sidebar     sidebar     ."
            ".  livingroom  livingroom  ."
            ".  kitchen     other       ."
            ".  media       flows       ."
            ".  .           .           ."
        #portrait
        "(max-width: 1200px)":
          grid-gap: var(--custom-layout-card-padding)
          grid-template-columns: repeat(3, 1fr) 0
          grid-template-rows: 0 repeat(3, fit-content(100%)) 0fr
          grid-template-areas: |
            "sidebar  .           .           ."
            "sidebar  livingroom  livingroom  ."
            "sidebar  kitchen     other       ."
            "sidebar  media       flows       ."
            "sidebar  .           .           ."
    cards:

      - type: custom:button-card
        styles: #extra_styles fix
          card:
            - display: none

      #################################################
      #                                               #
      #                    SIDEBAR                    #
      #                                               #
      #################################################

      - type: vertical-stack
        view_layout:
          grid-area: sidebar
        cards:
          - type: custom:button-card
            entity: sensor.template_sidebar
            template: sidebar_template

          #- type: horizontal-stack
          - type: grid
            columns: 4
            cards:
              - type: button
                icon: mdi:information-outline
                tap_action:
                  !include popup/sidebar_information.yaml
                hold_action:
                  action: none

              - type: button
                icon: mdi:arrow-up-bold-circle-outline
                tap_action:
                  !include popup/sidebar_update.yaml
                hold_action:
                  action: call-service
                  service: homeassistant.update_entity
                  service_data:
                    entity_id: sensor.hacs

      #################################################
      #                                               #
      #                  LIVINGROOM                   #
      #                                               #
      #################################################

      - type: grid
        title: Woonkamer
        view_layout:
          grid-area: livingroom
        columns: 4
        cards:

          - type: custom:button-card
            entity: light.led_lamp_woonkamer
            name: Led lamp
            template:
              - light_dimable
              - icon_hue

          - type: custom:button-card
            entity: switch.staande_lamp_aangezet
            name: Staande lamp
            template:
              - base
              - icon_lamp

          - type: custom:button-card
            entity: media_player.denonavr_x4100w
            name: Denon
            hold_action:
              !include popup/denon_avr.yaml
            template:
              - base
              - icon_tv
              - loader
              
          - type: custom:button-card
            entity: light.tv_meubel_verlichting
            name: TV Meubel
            template:
              - light_dimable
              - icon_hue
              
          - type: custom:button-card
            entity: switch.dressior_lamp_aangezet
            name: Dressior
            template:
              - base
              - icon_shade

          - type: custom:button-card
            entity: light.living_colors_2
            # hold_action:
            #   !include popup/vardagsrum_balkong.yaml
            template:
              - light_rgbw
              - icon_bloom

          - type: custom:button-card
            entity: light.nanoleaf_canvas
            name: Nanoleaf
            # hold_action:
            #   !include popup/vardagsrum_balkong.yaml
            template:
              - light_rgbw
              - icon_nanoleaf

          - type: custom:button-card
            entity: cover.gordijnen_woonkamer
            name: Gordijn
            template:
              - curtain
              - icon_curtains

      #################################################
      #                                               #
      #                    KITCHEN                    #
      #                                               #
      #################################################

      - type: grid
        title: Keuken
        view_layout:
          grid-area: kitchen
        columns: 2
        cards:

          - type: custom:button-card
            entity: switch.keuken_lamp_aangezet
            name: Keuken lamp
            template:
              - base
              - icon_hue

          - type: custom:button-card
            entity: switch.eettafel_lamp_aangezet
            name: Tafellamp
            template:
              - base
              - icon_lamp_table

          - type: custom:button-card
            entity: light.mechanische_ventilator
            name: Ventilator
            template:
              - fan
              - icon_fan

      #################################################
      #                                               #
      #                     MEDIA                     #
      #                                               #
      #################################################

      - type: grid
        title: Media
        view_layout:
          grid-area: media
        columns: 1
        cards:

          - type: custom:button-card
            entity: media_player.spotify_mylke_baas
            name: Spotify
            template:
              - conditional_media
              - icon_spotify

      #################################################
      #                                               #
      #                    OTHER                      #
      #                                               #
      #################################################

      - type: grid
        title: Overig
        view_layout:
          grid-area: other
        columns: 2
        cards:

          - type: custom:button-card
            entity: switch.hal_lamp_aangezet
            name: Gang lamp
            template:
              - base
              - icon_closet

          - type: custom:button-card
            entity: switch.overloop_1e_aangezet
            name: Overloop
            template:
              - base
              - icon_spot

          - type: custom:button-card
            entity: light.led_strip
            # hold_action:
            #   !include popup/vardagsrum_balkong.yaml
            template:
              - light_rgbw
              - icon_hue

      #################################################
      #                                               #
      #                     FLOWS                     #
      #                                               #
      #################################################

      - type: grid
        title: Flows
        view_layout:
          grid-area: flows
        columns: 2
        cards:

          - type: custom:button-card
            name: Film mode
            tap_action:
              action: call-service
              service: mqtt.publish
              service_data:
                topic: homie/homey/flow/movie
            template:
              - flow
              - icon_movie

          - type: custom:button-card
            name: Slapen
            icon: mdi:bed
            tap_action:
              action: call-service
              service: mqtt.publish
              service_data:
                topic: homie/homey/flow/slapen
            template:
              - flow
              - icon_bed

          - type: custom:button-card
            name: Alles Uit
            icon: mdi:lightbulb-group-off
            tap_action:
              action: call-service
              service: mqtt.publish
              service_data:
                topic: homie/homey/flow/alles_uit
            template:
              - flow
              - icon_all_off

          - type: custom:button-card
            name: Open Gordijnen
            icon: mdi:curtains
            tap_action:
              action: call-service
              service: mqtt.publish
              service_data:
                topic: homie/homey/flow/open_gordijnen
            template:
              - flow
              - icon_curtains
