homeassistant:
  customize:

    ####################################################
    #                                                  #
    #                    CUSTOMIZE                     #
    #                                                  #
    ####################################################

    #media_player
    media_player.spotify:
      friendly_name: Spotify

    #sidebar_information.yaml
    switch.watchtower:
      icon: custom:docker-watchtower
    sensor.databas:
      icon: mdi:database
    sensor.home_assistant_log:
      friendly_name: Logfile
      icon: mdi:file-document
    sensor.uptime:
      friendly_name: Laatste herstart
      icon: mdi:update
      device_class: timestamp
    sensor.docker_cpu:
      friendly_name: Processor
      icon: mdi:chip
    sensor.processor_use_percent:
      icon: mdi:chip
      
    # studio_monitorer.yaml just for refrence
    automation.eq_calibration:
      friendly_name: Automatisk kalibrationsprofil
      icon: custom:eq-calibrate
    
    #sort
    # sensor.rpi_cpu:
    #   friendly_name: Processor
    #   icon: mdi:chip
    # sensor.rpi_mem:
    #   friendly_name: Minne
    #   icon: mdi:memory
    # sensor.rpi_sd:
    #   friendly_name: SD-kort
    #   icon: mdi:micro-sd
    # sensor.rpi_uptime:
    #   friendly_name: Laatste herstart
    #   icon: mdi:update
    #   device_class: timestamp
